import { describe, expect, it } from 'vitest'

import {
  extractClangRuntimeSearchPaths,
  hasStaleClangRuntimePath,
  isPackageBuildDirectory,
} from '../ensure-clang-runtime-cache.mjs'

const currentRuntimePath =
  '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/21/lib/darwin'

describe('ensure-clang-runtime-cache', () => {
  it('extracts native and non-native Clang runtime search paths', () => {
    const output = [
      'cargo:rustc-link-search=native=/usr/lib/swift',
      `cargo:rustc-link-search=${currentRuntimePath}`,
      `cargo:rustc-link-search=native=${currentRuntimePath}`,
    ].join('\n')

    expect(extractClangRuntimeSearchPaths(output)).toEqual([currentRuntimePath, currentRuntimePath])
  })

  it('accepts an empty or current cache', () => {
    expect(hasStaleClangRuntimePath('', currentRuntimePath)).toBe(false)
    expect(
      hasStaleClangRuntimePath(`cargo:rustc-link-search=${currentRuntimePath}`, currentRuntimePath),
    ).toBe(false)
  })

  it('detects a cache generated by an older Xcode Clang version', () => {
    const staleOutput =
      'cargo:rustc-link-search=/Applications/Xcode.app/Contents/Developer/Toolchains/' +
      'XcodeDefault.xctoolchain/usr/lib/clang/17/lib/darwin'

    expect(hasStaleClangRuntimePath(staleOutput, currentRuntimePath)).toBe(true)
  })

  it('ignores unrelated linker search paths', () => {
    const output = [
      'cargo:rustc-link-search=native=/usr/lib/swift',
      'cargo:rustc-link-search=native=/tmp/project/release',
    ].join('\n')

    expect(hasStaleClangRuntimePath(output, currentRuntimePath)).toBe(false)
  })

  it('does not confuse the tauri package with tauri plugins', () => {
    expect(isPackageBuildDirectory('tauri-37f877be93d1503a', 'tauri')).toBe(true)
    expect(isPackageBuildDirectory('tauri-plugin-log-ac137797a912145c', 'tauri')).toBe(false)
  })
})
